name: My experimental pipeline
on:
  push

jobs:
  run-python-hello-world:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up Python 3.10.10
        uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.10.10
      - name: Print the version of Python
        run: python --version
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
      - name: Run the Python-written hello world
        run: ./hello_world.py
  run-ruby-hello-world:
    runs-on: ubuntu-22.04
    steps:
      # - name: Set up Python 3.10.10
      #   uses: actions/setup-python@v4.6.1
      #   with:
      #     python-version: 3.10.10
      - name: Print the version of Ruby
        run: ruby --version
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
      - name: Run the Ruby-written hello world
        run: ./hello_world.rb
