on:
  push

jobs:
  run-hello-world:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v4.6.1
        with:
          python-version: 3.10.10
      - run: python --version
      - uses: actions/checkout@v3.5.3
      - run: ./hello_world.py
